# Generated by Django 4.1.1 on 2022-10-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year_released',
            field=models.IntegerField(),
        ),
    ]
