# Generated by Django 4.1.1 on 2022-10-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0004_alter_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
