# Generated by Django 4.1.1 on 2022-10-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0005_alter_developer_developer_id_alter_genre_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
