# Generated by Django 4.1.1 on 2022-10-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0006_alter_game_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
