# Generated by Django 4.1.1 on 2022-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0007_alter_game_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
