# Generated by Django 4.1.1 on 2022-10-14 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0010_alter_game_sales_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sales_id',
        ),
        migrations.AddField(
            model_name='game',
            name='sales_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='registergame.sales'),
            preserve_default=False,
        ),
    ]
