# Generated by Django 4.1.1 on 2022-10-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0011_remove_game_sales_id_game_sales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
