# Generated by Django 4.1.1 on 2022-10-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('developer_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('developer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('year_released', models.DateField()),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registergame.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('evaluation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=69)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales', models.FloatField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registergame.game')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registergame.region')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registergame.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registergame.platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='rating_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registergame.rating'),
        ),
    ]
