# Generated by Django 4.1.1 on 2022-10-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='game_id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='sales_id',
            field=models.ManyToManyField(to='registergame.sales'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='year_released',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
