# Generated by Django 4.1.1 on 2022-10-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0002_remove_sales_game_id_game_game_img_game_sales_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='sales_id',
            field=models.ManyToManyField(null=True, to='registergame.sales'),
        ),
    ]
