# Generated by Django 4.1.1 on 2022-10-15 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0004_alter_sales_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sales_id',
        ),
        migrations.AddField(
            model_name='sales',
            name='game_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registergame.game'),
            preserve_default=False,
        ),
    ]
