# Generated by Django 4.1 on 2022-10-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registergame', '0006_platform_platform_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
